### ISSUE TITLE
Can't inline SVG in stylesheets

### ISSUE THREAD

**Issue by RadValentin** [sairion/svg-inline-loader#22]
There's a problem with using this loader in that it makes in impossible to load SVGs in stylesheets. 

Would it be possible to change the output format to Data URI for certain file types? I'm thinking something similar to [this approach](http://codepen.io/terabaud/details/PZdaJo/)

```css
.input {
  background-image: url('path/file.svg')
}

.output {
  /* current output ... this won't work */
  background-image: url('<svg>...</svg>');

  /* but something like this might work*/
  background-image: url('data:image/svg+xml;utf8,%3Csvg...');
}
```
